spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: false
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
    database: H2